name: Latest blog post workflow

on:
  schedule:
    - cron: '0 3 * * *'   # Every day 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Update this repo's README with latest blog posts
        uses: actions/checkout@v4

      # Programming
      - name: Update Programming posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://buthonestly.io/programming/feed/"
          max_post_count: 3
          comment_tag_name: "PROGRAMMING"
          template: "<li><em>$date</em> <a href='$url'>$title</a></li>"
          date_format: "UTC: yyyy-mm-dd"

      # Leadership
      - name: Update Leadership posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://buthonestly.io/leadership/feed/"
          max_post_count: 3
          comment_tag_name: "LEADERSHIP"
          template: "<li><em>$date</em> <a href='$url'>$title</a></li>"
          date_format: "UTC: yyyy-mm-dd"

      # Web Tech
      - name: Update Web Tech posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://buthonestly.io/web/feed/"
          max_post_count: 3
          comment_tag_name: "WEB"
          template: "<li><em>$date</em> <a href='$url'>$title</a></li>"
          date_format: "UTC: yyyy-mm-dd"
