name: Latest blog post workflow

on:
  schedule:
    - cron: "0 3 * * 1-7"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # üêç Programming
      - name: Update Programming posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nicolamustone.blog/category/programming/feed/"
          max_post_count: 3
          comment_tag_name: "PROGRAMMING"
          template: "- [$title]($url)"

      # üß≠ Leadership
      - name: Update Leadership posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nicolamustone.blog/category/leadership/feed/"
          max_post_count: 3
          comment_tag_name: "LEADERSHIP"
          template: "- [$title]($url)"

      # üåê Web Tech
      - name: Update Web Tech posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://nicolamustone.blog/category/web/feed/"
          max_post_count: 3
          comment_tag_name: "WEB"
          template: "- [$title]($url)"
